"""
    all constants that need to correct system work
"""

LOCALHOST = "http://127.0.0.1"
PORT = "5000"

USERS_LINK = "/users"
USER_LINK = "/user"

GET_ALL_USERS_LINK = LOCALHOST + ":" + PORT + USERS_LINK
GET_USER_LINK = LOCALHOST + ":" + PORT + USER_LINK
POST_USER_LINK = LOCALHOST + ":" + PORT + USER_LINK
PUT_USER_LINK = LOCALHOST + ":" + PORT + USER_LINK
DELETE_USER_LINK = LOCALHOST + ":" + PORT + USER_LINK

GET_ALL_USERS_LINK_MISTAKE = GET_ALL_USERS_LINK + "."
GET_USER_LINK_MISTAKE = GET_USER_LINK + "."
POST_USER_LINK_MISTAKE = POST_USER_LINK + "."
PUT_USER_LINK_MISTAKE = PUT_USER_LINK + "."
DELETE_USER_LINK_MISTAKE = DELETE_USER_LINK + "."
