name: Py Tests
on:
  push:
    branches: [ master ]

jobs:
  flasktests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/python:dev-3.12
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Start Flask application
        run: |
          export FLASK_APP=userAPI.py
          flask run &
      
      - name: Run pytest
        run: pytest
